CREATE TABLE TASKS(
        TaskId INT AUTO_INCREMENT PRIMARY KEY,
        userId INT NOT NULL,
        Title VARCHAR(255) NOT NULL,
        Status VARCHAR(255) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)